site_name: SilverLite FS-i6 Firmware
nav:
    - Introduction: index.md
    - Flashing: Flashing.md
    - How to use: Manual.md
    - Setting up your development environment: devEnvSetup.md
    - NRF24L01 module: NRF24L01.md
    - Multiprotocol module: Multiprotocol.md
    - Channel configuration: ChannelConfig.md
    - Acknowledgements: Acknowledgements.md



theme:
  name: 'material'

# So that the sidebar links work correctly when using *file* server rather than a real web server
# we neeed to set `use_directory_urls` to False (default is True)
# IOW, comment out the following line if you're going to use a server to host the documentation
#use_directory_urls: False

